### ISSUE TITLE
Module doesn't build with kernel 5.8 and onwards.

### ISSUE THREAD

**Issue by xaltsc** [skylerpan/rtl88x2bu_dwa_181_driver#4]
On VoidLinux, using kernels 5.4, 5.6 and 5.7, I managed to get the DWA-181 working, however, on 5.8 and 5.11, it doesn't work anymore. Below is the `make.log` when I try to build on 5.8. The `make.log` on 5.11 was much longer and I can provide it here if you request it.

```
DKMS make.log for rtl88x2bu-5.6.1 for kernel 5.8.18_1 (x86_64)
Thu Mar 25 04:35:24 PM CET 2021
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.8.18_1/build M=/var/lib/dkms/rtl88x2bu/5.6.1/build  modules
make[1]: Entering directory '/usr/src/kernel-headers-5.8.18_1'
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_cmd.o
In file included from /var/lib/dkms/rtl88x2bu/5.6.1/build/include/drv_types.h:30,
                 from /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_cmd.c:17:
/var/lib/dkms/rtl88x2bu/5.6.1/build/include/wifi.h:1037: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 1037 | #define IEEE80211_MAX_AMPDU_BUF 0x40
      | 
In file included from /var/lib/dkms/rtl88x2bu/5.6.1/build/include/osdep_service_linux.h:83,
                 from /var/lib/dkms/rtl88x2bu/5.6.1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl88x2bu/5.6.1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_cmd.c:17:
./include/linux/ieee80211.h:1600: note: this is the location of the previous definition
 1600 | #define IEEE80211_MAX_AMPDU_BUF  0x100
      | 
In file included from /var/lib/dkms/rtl88x2bu/5.6.1/build/include/drv_types.h:79,
                 from /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_cmd.c:17:
/var/lib/dkms/rtl88x2bu/5.6.1/build/include/rtw_security.h:255:8: error: redefinition of 'struct sha256_state'
  255 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl88x2bu/5.6.1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl88x2bu/5.6.1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl88x2bu/5.6.1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1752: /var/lib/dkms/rtl88x2bu/5.6.1/build] Error 2
make[1]: Leaving directory '/usr/src/kernel-headers-5.8.18_1'
make: *** [Makefile:2247: modules] Error 2
```

**Comment by xaltsc** [comment]
As a side note, even though it works on 5.7, the speed is very slow.
